after_success: |
  if [ "$TRAVIS_SECURE_ENV_VARS" == true ]; then
    echo "$PGP_SECRET" | base64 --decode | gpg --import
    if [ -z "$TRAVIS_TAG" ]; then
        (cd sbt-cross && exec sbt publishSigned)
    else
        (cd sbt-cross && exec sbt "; ^publishSigned; sonatypeBundleRelease")
    fi
  fi
cache:
  directories:
    - $HOME/.ivy2
    - $HOME/.sbt
deploy:
  api_key: $GITHUB_AUTH
  file: '*/target/**/*.jar'
  file_glob: true
  on:
    tags: true
  provider: releases
  skip_cleanup: true
git:
  depth: 1
jdk: openjdk8
language: scala
script:
  - '[ "$TRAVIS_PULL_REQUEST" != false ] || export SBT_OPTS=-Dbuild.version=${TRAVIS_TAG:-$TRAVIS_BRANCH-SNAPSHOT}'
  - (cd sbt-cross && exec sbt '^all ^checkFormat ^package ^test')
